In [3]:
# DML(data manipulation language) using sqlite3 and python


from tkinter import *
import sqlite3
import tkinter.messagebox


root=Tk()
root.geometry('400x450')
root.title('DML Operations using sqlite3 and python')
root.configure(background='light grey')

db = sqlite3.connect('mysq.db')                   # creating DB
cursor = db.cursor()
cursor.execute("CREATE TABLE IF NOT EXISTS people(name TEXT, phone TEXT)")        # Table
db.commit()


textin=StringVar()
textinn=StringVar()
def insert():
    name1 = textin.get()
    phone1 = textinn.get()
    conn = sqlite3.connect('mysq.db')
    with conn:
        cursor = conn.cursor()
        cursor.execute('INSERT INTO people(name, phone) VALUES(?,?)',(name1, phone1,))
        tkinter.messagebox.showinfo('Welcome','submitted')
        db.close()

label1=Label(root,text='Name:', pady=2,font=('none 13 bold'))
label1.place(x=2,y=0)
entry1=Entry(root,width=20, font=('none 13'),textvar=textin)
entry1.place(x=80,y=0)

label2=Label(root,text='Phone:', pady=2,font=('none 13 bold'))
label2.place(x=2,y=40)
entry2=Entry(root,width=20,font=('none 13'),textvar=textinn)
entry2.place(x=80,y=40)

button1=Button(root,padx=2,pady=2,text='Submit', command=insert, font=('none 13 bold'))
button1.place(x=80,y=67)


def show():
    connt = sqlite3.connect('mysq.db')
    cursor= connt.cursor()
    cursor.execute('SELECT * FROM people')
    for row in cursor.fetchall():                       # fetchall()
        print(row)

button2=Button(root,padx=2,pady=2,text='Show', command=show, font=('none 13 bold'))
button2.place(x=0,y=127)
label=Label(root,text='It Shows Data of Table').place(x=70,y=135)



name=StringVar()
phone=StringVar()
def updateContact():
    name2=name.get()
    phone2=phone.get()

    con = sqlite3.connect('mysq.db')
    cursor = con.cursor()
    cursor.execute('UPDATE people SET name = ? WHERE phone = ?', (name2,phone2))
    tkinter.messagebox.showinfo('hey', 'Name Updated')
    con.commit()

label3=Label(root,text='Update Name :',font=('none 13 bold'))
label3.place(x=0,y=200)
entry3=Entry(root,width=20,font=('none 13 '),textvar=name)
entry3.place(x=200,y=200)

label4=Label(root,text='Provide Phone No. :',font=('none 13 bold'))
label4.place(x=0,y=240)
entry4=Entry(root,width=20,font=('none 13'),textvar=phone)
entry4.place(x=200,y=240)
label=Label(root, text='contact must be earlier one').place(x=0,y=266)

button3=Button(root,padx=2,pady=2,text='Update',command=updateContact,font=('none 13 bold'),relief='raise')
button3.place(x=200,y=270)


delete=StringVar()
def dell():
    delete1=delete.get()
    con_del = sqlite3.connect('mysq.db')
    cursor = con_del.cursor()
    cursor.execute('DELETE FROM people WHERE name = ?', (delete1,))
    tkinter.messagebox.showinfo('Deleted', 'Name and Phone number is Deleted')
    con_del.commit()

label5=Label(root,text='Delete :',font=('none 13 bold'))
label5.place(x=0,y=380)
entry5=Entry(root,width=20,textvar=delete,font=('none 13'))
entry5.place(x=90,y=380)

button4=Button(root,padx=2,pady=2,text='Delete',command=dell, font=('none 13 bold'))
button4.place(x=90,y=405)


def drop():
    connnt=sqlite3.connect('mysq.db')
    cursor = connnt.cursor()
    cursor.execute("DROP table people")
    tkinter.messagebox.showinfo('DELETED !!', 'Data table is Deleted')
    connnt.commit()

buttdrop=Button(root,padx=2,pady=2,text='Drop table',command=drop,font=('none 13 bold'),relief='raise')
buttdrop.place(x=295,y=410)

root.mainloop()